### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by punkoffice** [TrevorDev/babylonServer#1]
This project looks promising, however, I can't get it to work.
webpack completes (with some deprecation warnings) but when I `npm start` it stalls, like it drags down the whole server where I can't even type on another terminal.

**Comment by TrevorDev** [comment]
Maybe you need a more powerful server as this is a bit heavy. I havn't touched this in ages so i wouldn't expect much.

**Comment by punkoffice** [comment]
This was actually really useful advice.  webpack will not run on an AWS t2.micro because its too weak.  So I used WSL on my Windows computer

What I did was first update all the packages:
`npm install -g npm-check-updates`
`ncu --upgrade`
`npm install`

ran `webpack`
then I copied `server.js` and `public/dist/testApp.js` to my t2.micro server then I can run:
`npm start`
and it works fine.  So its all good as long as I build the webpack on a powerful server
